export const COPY = {
  id: {
    nav: {
      home: 'BERANDA',
      manifesto: 'MANIFESTO',
      wallpapers: 'WALLPAPER',
      tutorials: 'KELAS',
      community: 'KOMUNITAS',
      journal: 'TONTON',
    },
    heroTag: '1% PER HARI.',
    onePctLabel: 'KENAPA SATU PERSEN',
    onePctBody:
      'Bukan transformasi. Bukan keajaiban semalam. Cuma satu persen lebih baik dari kemarin, diulang seribu kali. Disiplin yang nggak keliatan hari ini jadi hasil yang nggak bisa diabaikan tahun depan.',
    onePctSub: '1% setiap hari = 37x lebih baik dalam setahun.',
    fwLabel: 'PILIHAN · 9:16',
    fwTitle: 'Wallpaper buat layar lo.',
    fwCta: 'SEMUA 12 →',
    interOneSub: 'Pelan bukan berarti berhenti.',
    packsLabel: 'KELAS EDIT',
    packsTitle: 'Belajar dari nol sampai jadi.',
    packsSub: 'Tiga paket. Satu metode. Tanpa teori basi.',
    interTwoSub: 'Jatuh itu wajar. Diam yang bahaya.',
    discordLabel: 'KOMUNITAS',
    discordTitle: 'Lo nggak harus sendirian.',
    discordBody:
      'Ribuan orang lagi ngejar hal yang sama. Masuk, posting progress lo, dan biarin grup yang jagain konsistensi lo.',
    discordCta: 'Gabung Discord',
    wp: { buy: 'Beli →' },
    tut: { take: 'Ambil →' },
    deviceNotif: { time: 'sekarang', msg: '1% hari ini. Udah belum?' },
    manifesto: {
      kicker: 'MANIFESTO · 001',
      title: '1% Per Hari.',
      lead: 'Lo nggak butuh hari yang sempurna. Lo butuh hari yang dikerjain.',
      body: [
        'Semua orang pengen lompatan. Pengen bangun besok jadi orang yang beda. Tapi perubahan nggak kerja kayak gitu. Perubahan itu pelan, ngebosenin, dan hampir nggak keliatan pas lagi terjadi.',
        'Satu persen hari ini nggak akan ngubah apa apa. Lo nggak bakal ngerasain bedanya. Tapi satu persen yang diulang, hari demi hari, numpuk jadi sesuatu yang nggak bisa lo bohongin. Itu bukan motivasi. Itu matematika.',
        'Hari hari yang males adalah ujian sebenarnya. Siapa pun bisa kerja pas lagi semangat. Yang bikin lo beda adalah pas lo tetap muncul walau nggak ada yang nonton, walau nggak ada yang peduli, walau lo sendiri ragu.',
        'Jadi berhenti nunggu momen yang tepat. Berhenti nyari versi diri lo yang udah jadi. Mulai dari satu persen. Hari ini. Lagi.',
      ],
      pull1: 'Disiplin adalah jembatan antara mimpi dan kenyataan.',
      pull2: 'Konsistensi ngalahin bakat yang nggak pernah muncul.',
      signature: '— INNOSXNCE',
    },
    wpPage: {
      kicker: 'KOLEKSI · 12',
      title: 'Wallpaper',
      sub: 'Dua belas pengingat. Satu gaya. Pasang di layar, liat tiap hari.',
      bundleLabel: 'BUNDLE',
      bundleTitle: 'Ambil semua sekaligus.',
      bundleBody: 'Akses penuh ke dua belas wallpaper, plus update di masa depan. Sekali bayar.',
      bundleCta: 'Beli Bundle →',
    },
    tutPage: {
      kicker: 'KELAS · 03',
      title: 'Tutorial Pack',
      sub: 'Dari ngerti tombol sampai ngerti rasa. Belajar ngedit kayak yang lo liat di feed.',
      previewLabel: 'PREVIEW',
      previewTitle: 'Lihat dulu sebelum beli.',
      previewBody: 'Satu pelajaran gratis dari tiap paket. Nggak ada yang disembunyiin.',
      previewCta: 'Tonton Preview →',
    },
    community: {
      kicker: 'KOMUNITAS',
      title: 'Masuk Barisan.',
      sub: 'Tempat lo dijagain biar nggak balik ke kebiasaan lama.',
      stats: [
        { n: '12.4K', l: 'MEMBER' },
        { n: '2.1K', l: 'AKTIF / HARI' },
        { n: '24/7', l: 'HIDUP' },
        { n: 'FREE', l: 'GRATIS' },
      ],
      benefits: [
        { t: 'Akuntabilitas', d: 'Posting target mingguan lo. Grup yang nagih kalau lo ngilang.' },
        { t: 'Kritik Edit', d: 'Upload editan lo, dapet feedback jujur dari yang udah jago.' },
        { t: 'Drop Materi', d: 'Preset, sound, dan template dibagiin tiap minggu.' },
        { t: 'Sesi Live', d: 'Ngedit bareng dan tanya jawab langsung tiap bulan.' },
      ],
      cta: 'Gabung Discord →',
    },
    journal: {
      kicker: 'TONTON',
      title: 'Semua ada di TikTok.',
      sub: 'Konten harian, edit pendek, dan pengingat satu persen. Update tiap hari di @innosxnce1.',
      cta: 'Tonton di TikTok →',
      videos: [
        { t: 'Cara mulai pas lagi nggak mood', v: '1.2M' },
        { t: 'Satu persen, dijelasin 30 detik', v: '890K' },
        { t: 'Rutinitas pagi tanpa drama', v: '2.4M' },
      ],
    },
    footerMade: '© 2026 INNOSXNCE · DIBUAT DI TANGERANG SELATAN',
    footerDisc:
      'Semua pembelian diproses lewat Lynk.id. Dengan membeli, kamu setuju sama ketentuan yang berlaku di platform tersebut.',
  },
  en: {
    nav: {
      home: 'HOME',
      manifesto: 'MANIFESTO',
      wallpapers: 'WALLPAPERS',
      tutorials: 'CLASSES',
      community: 'COMMUNITY',
      journal: 'WATCH',
    },
    heroTag: 'One percent better. Every day. No compromise. No drama.',
    onePctLabel: 'WHY ONE PERCENT',
    onePctBody:
      'Not a transformation. Not an overnight miracle. Just one percent better than yesterday, repeated a thousand times. The discipline nobody sees today becomes a result nobody can ignore next year.',
    onePctSub: '1% every day = 37x better in a year.',
    fwLabel: 'FEATURED · 9:16',
    fwTitle: 'Wallpapers for your screen.',
    fwCta: 'ALL 12 →',
    interOneSub: 'Slow is not the same as stopped.',
    packsLabel: 'EDIT CLASSES',
    packsTitle: 'Learn from zero to finished.',
    packsSub: 'Three packs. One method. No stale theory.',
    interTwoSub: 'Falling is normal. Staying down is the danger.',
    discordLabel: 'COMMUNITY',
    discordTitle: 'You do not have to do it alone.',
    discordBody:
      'Thousands of people chasing the same thing. Get in, post your progress, and let the room hold your consistency.',
    discordCta: 'Join Discord',
    wp: { buy: 'Buy →' },
    tut: { take: 'Get →' },
    deviceNotif: { time: 'now', msg: '1% today. Did you?' },
    manifesto: {
      kicker: 'MANIFESTO · 001',
      title: '1% A Day.',
      lead: 'You do not need a perfect day. You need a day you actually worked.',
      body: [
        'Everyone wants the leap. To wake up tomorrow as a different person. But change does not work that way. Change is slow, boring, and almost invisible while it is happening.',
        'One percent today changes nothing. You will not feel the difference. But one percent repeated, day after day, stacks into something you cannot lie about. That is not motivation. That is math.',
        'The lazy days are the real test. Anyone can work when they feel inspired. What sets you apart is showing up when no one is watching, when no one cares, when even you have doubts.',
        'So stop waiting for the right moment. Stop looking for the finished version of yourself. Start with one percent. Today. Again.',
      ],
      pull1: 'Discipline is the bridge between dreams and reality.',
      pull2: 'Consistency beats talent that never shows up.',
      signature: '— INNOSXNCE',
    },
    wpPage: {
      kicker: 'COLLECTION · 12',
      title: 'Wallpapers',
      sub: 'Twelve reminders. One look. Set your screen, see it every day.',
      bundleLabel: 'BUNDLE',
      bundleTitle: 'Take the whole set.',
      bundleBody: 'Full access to all twelve wallpapers, plus future updates. One payment.',
      bundleCta: 'Buy Bundle →',
    },
    tutPage: {
      kicker: 'CLASSES · 03',
      title: 'Tutorial Packs',
      sub: 'From knowing the buttons to knowing the feel. Edit like the work you see on your feed.',
      previewLabel: 'PREVIEW',
      previewTitle: 'Look before you buy.',
      previewBody: 'One free lesson from every pack. Nothing hidden.',
      previewCta: 'Watch Preview →',
    },
    community: {
      kicker: 'COMMUNITY',
      title: 'Join the Line.',
      sub: 'A room that keeps you from slipping back into old habits.',
      stats: [
        { n: '12.4K', l: 'MEMBERS' },
        { n: '2.1K', l: 'ACTIVE / DAY' },
        { n: '24/7', l: 'ALIVE' },
        { n: 'FREE', l: 'FREE' },
      ],
      benefits: [
        { t: 'Accountability', d: 'Post your weekly target. The room calls you out when you go quiet.' },
        { t: 'Edit Critique', d: 'Upload your edits, get honest feedback from people who can already do it.' },
        { t: 'Resource Drop', d: 'Presets, sounds and templates shared every week.' },
        { t: 'Live Calls', d: 'Edit together and ask anything live, every month.' },
      ],
      cta: 'Join Discord →',
    },
    journal: {
      kicker: 'WATCH',
      title: 'It all lives on TikTok.',
      sub: 'Daily content, short edits and one percent reminders. New every day at @innosxnce1.',
      cta: 'Watch on TikTok →',
      videos: [
        { t: 'How to start when the mood is gone', v: '1.2M' },
        { t: 'One percent, explained in 30 seconds', v: '890K' },
        { t: 'A morning routine with no drama', v: '2.4M' },
      ],
    },
    footerMade: '© 2026 INNOSXNCE · MADE IN TANGERANG SELATAN',
    footerDisc:
      'All purchases are processed through Lynk.id. By buying, you agree to the terms that apply on that platform.',
  },
} as const

export type CopyType = typeof COPY
export type LangCopy = CopyType['id']
