export const COPY = {
  id: {
    nav: {
      home: 'BERANDA',
      wallpapers: 'WALLPAPER',
      tutorials: 'KELAS',
      // Tidak lagi di nav utama — dipakai untuk link internal di footer.
      community: 'KOMUNITAS',
      business: 'BISNIS',
    },
    heroTag: '1% PER HARI.',
    onePctLabel: 'KENAPA SATU PERSEN',
    onePctBody:
      'Bukan transformasi. Bukan keajaiban semalam. Cuma satu persen lebih baik dari kemarin, diulang seribu kali. Disiplin yang nggak keliatan hari ini jadi hasil yang nggak bisa diabaikan tahun depan.',
    onePctSub: '1% setiap hari = 37x lebih baik dalam setahun.',
    // Diselamatkan dari halaman Manifesto yang dihapus.
    onePctLine: 'Konsistensi ngalahin bakat yang nggak pernah muncul.',
    fwLabel: 'PILIHAN · 9:16',
    fwTitle: 'Wallpaper buat layar lo.',
    fwCta: 'SEMUA 12 →',
    packsLabel: 'KELAS EDIT',
    packsTitle: 'Belajar dari nol sampai jadi.',
    packsSub: 'Tiga paket. Satu metode. Tanpa teori basi.',
    discordLabel: 'KOMUNITAS',
    discordTitle: 'Lo nggak harus sendirian.',
    discordBody:
      'Ribuan orang lagi ngejar hal yang sama. Masuk, posting progress lo, dan biarin grup yang jagain konsistensi lo.',
    discordCta: 'Gabung Discord',
    wp: { buy: 'Beli →' },
    tut: { take: 'Ambil →' },
    deviceNotif: { time: 'sekarang', msg: '1% hari ini. Udah belum?' },
    wpPage: {
      kicker: 'KOLEKSI · 12',
      title: 'Wallpaper',
      sub: 'Dua belas pengingat. Satu gaya. Pasang di layar, liat tiap hari.',
      bundleLabel: 'BUNDLE',
      bundleTitle: 'Ambil semua sekaligus.',
      bundleBody: 'Akses penuh ke dua belas wallpaper, plus update di masa depan. Sekali bayar.',
      bundleCta: 'Beli Bundle →',
    },
    tutPage: {
      kicker: 'KELAS · 03',
      title: 'Tutorial Pack',
      sub: 'Dari ngerti tombol sampai ngerti rasa. Belajar ngedit kayak yang lo liat di feed.',
      previewLabel: 'PREVIEW',
      previewTitle: 'Lihat dulu sebelum beli.',
      previewBody: 'Satu pelajaran gratis dari tiap paket. Nggak ada yang disembunyiin.',
      previewCta: 'Tonton Preview →',
    },
    community: {
      kicker: 'KOMUNITAS',
      title: 'Masuk Barisan.',
      sub: 'Tempat lo dijagain biar nggak balik ke kebiasaan lama.',
      stats: [
        { n: '12.4K', l: 'MEMBER' },
        { n: '2.1K', l: 'AKTIF / HARI' },
        { n: '24/7', l: 'HIDUP' },
        { n: 'FREE', l: 'GRATIS' },
      ],
      benefits: [
        { t: 'Akuntabilitas', d: 'Posting target mingguan lo. Grup yang nagih kalau lo ngilang.' },
        { t: 'Kritik Edit', d: 'Upload editan lo, dapet feedback jujur dari yang udah jago.' },
        { t: 'Drop Materi', d: 'Preset, sound, dan template dibagiin tiap minggu.' },
        { t: 'Sesi Live', d: 'Ngedit bareng dan tanya jawab langsung tiap bulan.' },
      ],
      cta: 'Gabung Discord →',
    },
    inno: {
      kicker: 'INNOPRODUCTIONS · RUMAH PRODUKSI',
      title: 'Kami yang\nngedit.',
      lead: 'InnoProductions adalah sisi bisnis dari INNOSXNCE. Kamu kirim footage mentah, kami kirim balik video yang layak diupload — shortform, longform, atau keduanya.',
      ctaPrimary: 'Mulai Proyek →',
      ctaSecondary: 'Lihat Harga',
      relation:
        'INNOSXNCE adalah brand kreatornya. InnoProductions adalah studio yang ngerjain. Skill yang sama, cuma kali ini buat channel kamu.',

      servicesLabel: 'LAYANAN · 03',
      servicesTitle: 'Tiga cara kerjanya.',
      servicesSub: 'Semua dikerjain manual. Nggak ada template yang tinggal diisi.',

      workLabel: 'HASIL KERJA',
      workTitle: 'Geser buat lihat bedanya.',
      workSub: 'Kiri footage mentah. Kanan hasil akhir. Selisihnya itu yang kamu bayar.',
      workBefore: 'MENTAH',
      workAfter: 'HASIL',
      workHint: 'Geser · atau pakai tombol panah',

      processLabel: 'ALUR KERJA · 04',
      processTitle: 'Dari brief sampai file final.',
      processSub: 'Nggak ada tahap yang disembunyiin. Kamu selalu tahu posisi proyeknya di mana.',

      pricingLabel: 'HARGA',
      pricingTitle: 'Angkanya di depan.',
      pricingSub: 'Nggak perlu nanya dulu buat tahu harga. Semua sudah termasuk revisi dan file siap upload.',
      pricingFeatured: 'PALING SERING DIAMBIL',
      pricingPick: 'Ambil Paket →',
      pricingNote:
        'Harga di atas untuk lingkup standar. Proyek dengan footage sangat panjang, animasi berat, atau deadline mepet dihitung terpisah — tanya aja, penawarannya gratis.',

      addonsLabel: 'TAMBAHAN',
      addonsTitle: 'Bisa ditambah kapan aja.',
      addonsSub: 'Dibeli terpisah atau digabung ke paket mana pun.',

      faqLabel: 'PERTANYAAN',
      faqTitle: 'Yang biasanya ditanya.',

      contactLabel: 'MULAI',
      contactTitle: 'Ceritain proyeknya.',
      contactSub: 'Isi brief singkat ini. Formnya otomatis nyusun pesan — tinggal pilih mau dikirim lewat WhatsApp atau email.',
      contactDirect: 'Atau langsung aja:',

      form: {
        name: 'Nama / brand',
        namePh: 'Siapa yang aku ajak ngomong?',
        type: 'Tipe proyek',
        typeOpts: ['Shortform (Reels / TikTok / Shorts)', 'Longform (YouTube)', 'Podcast clipping', 'Retainer bulanan', 'Belum yakin'],
        qty: 'Jumlah video',
        qtyPh: 'contoh: 4',
        dur: 'Perkiraan durasi hasil',
        durPh: 'contoh: 60 detik / 12 menit',
        deadline: 'Deadline',
        footage: 'Link footage',
        footagePh: 'Google Drive / WeTransfer / Dropbox',
        notes: 'Referensi & catatan',
        notesPh: 'Gaya edit yang kamu suka, mood, atau apa pun yang perlu aku tahu.',
        optional: 'opsional',
        required: 'wajib',
        sendWa: 'Kirim via WhatsApp →',
        sendMail: 'Kirim via Email →',
        subject: 'Brief Proyek — InnoProductions',
        missing: 'Isi dulu nama dan tipe proyeknya.',
        greeting: 'Halo InnoProductions, aku mau order edit video.',
      },
    },
    footerMade: '© 2026 INNOSXNCE · DIBUAT DI TANGERANG SELATAN',
    footerDisc:
      'Semua pembelian diproses lewat Lynk.id. Dengan membeli, kamu setuju sama ketentuan yang berlaku di platform tersebut.',
  },
  en: {
    nav: {
      home: 'HOME',
      wallpapers: 'WALLPAPERS',
      tutorials: 'CLASSES',
      // No longer in the main nav — used for the internal footer link.
      community: 'COMMUNITY',
      business: 'BUSINESS',
    },
    heroTag: 'One percent better. Every day. No compromise. No drama.',
    onePctLabel: 'WHY ONE PERCENT',
    onePctBody:
      'Not a transformation. Not an overnight miracle. Just one percent better than yesterday, repeated a thousand times. The discipline nobody sees today becomes a result nobody can ignore next year.',
    onePctSub: '1% every day = 37x better in a year.',
    // Salvaged from the deleted Manifesto page.
    onePctLine: 'Consistency beats talent that never shows up.',
    fwLabel: 'FEATURED · 9:16',
    fwTitle: 'Wallpapers for your screen.',
    fwCta: 'ALL 12 →',
    packsLabel: 'EDIT CLASSES',
    packsTitle: 'Learn from zero to finished.',
    packsSub: 'Three packs. One method. No stale theory.',
    discordLabel: 'COMMUNITY',
    discordTitle: 'You do not have to do it alone.',
    discordBody:
      'Thousands of people chasing the same thing. Get in, post your progress, and let the room hold your consistency.',
    discordCta: 'Join Discord',
    wp: { buy: 'Buy →' },
    tut: { take: 'Get →' },
    deviceNotif: { time: 'now', msg: '1% today. Did you?' },
    wpPage: {
      kicker: 'COLLECTION · 12',
      title: 'Wallpapers',
      sub: 'Twelve reminders. One look. Set your screen, see it every day.',
      bundleLabel: 'BUNDLE',
      bundleTitle: 'Take the whole set.',
      bundleBody: 'Full access to all twelve wallpapers, plus future updates. One payment.',
      bundleCta: 'Buy Bundle →',
    },
    tutPage: {
      kicker: 'CLASSES · 03',
      title: 'Tutorial Packs',
      sub: 'From knowing the buttons to knowing the feel. Edit like the work you see on your feed.',
      previewLabel: 'PREVIEW',
      previewTitle: 'Look before you buy.',
      previewBody: 'One free lesson from every pack. Nothing hidden.',
      previewCta: 'Watch Preview →',
    },
    community: {
      kicker: 'COMMUNITY',
      title: 'Join the Line.',
      sub: 'A room that keeps you from slipping back into old habits.',
      stats: [
        { n: '12.4K', l: 'MEMBERS' },
        { n: '2.1K', l: 'ACTIVE / DAY' },
        { n: '24/7', l: 'ALIVE' },
        { n: 'FREE', l: 'FREE' },
      ],
      benefits: [
        { t: 'Accountability', d: 'Post your weekly target. The room calls you out when you go quiet.' },
        { t: 'Edit Critique', d: 'Upload your edits, get honest feedback from people who can already do it.' },
        { t: 'Resource Drop', d: 'Presets, sounds and templates shared every week.' },
        { t: 'Live Calls', d: 'Edit together and ask anything live, every month.' },
      ],
      cta: 'Join Discord →',
    },
    inno: {
      kicker: 'INNOPRODUCTIONS · PRODUCTION HOUSE',
      title: 'We do\nthe edit.',
      lead: 'InnoProductions is the business side of INNOSXNCE. You send the raw footage, we send back a video worth publishing — shortform, longform, or both.',
      ctaPrimary: 'Start a Project →',
      ctaSecondary: 'See Pricing',
      relation:
        'INNOSXNCE is the creator brand. InnoProductions is the studio that does the work. Same craft, pointed at your channel this time.',

      servicesLabel: 'SERVICES · 03',
      servicesTitle: 'Three ways in.',
      servicesSub: 'All cut by hand. No fill-in-the-blank templates.',

      workLabel: 'THE WORK',
      workTitle: 'Drag to see the difference.',
      workSub: 'Raw footage on the left. Finished cut on the right. The gap is what you are paying for.',
      workBefore: 'RAW',
      workAfter: 'FINAL',
      workHint: 'Drag · or use the arrow keys',

      processLabel: 'PROCESS · 04',
      processTitle: 'From brief to final file.',
      processSub: 'No hidden stage. You always know where the project stands.',

      pricingLabel: 'PRICING',
      pricingTitle: 'Numbers up front.',
      pricingSub: 'No need to ask before you know the cost. Revisions and upload-ready files are already in.',
      pricingFeatured: 'MOST CHOSEN',
      pricingPick: 'Take This →',
      pricingNote:
        'These prices cover standard scope. Projects with very long footage, heavy animation or a tight deadline are quoted separately — just ask, quoting is free.',

      addonsLabel: 'ADD-ONS',
      addonsTitle: 'Bolt on anything.',
      addonsSub: 'Bought on their own or attached to any package.',

      faqLabel: 'QUESTIONS',
      faqTitle: 'What people usually ask.',

      contactLabel: 'START',
      contactTitle: 'Tell me about the project.',
      contactSub: 'Fill in this short brief. The form assembles the message for you — just pick WhatsApp or email to send it.',
      contactDirect: 'Or go direct:',

      form: {
        name: 'Name / brand',
        namePh: 'Who am I talking to?',
        type: 'Project type',
        typeOpts: ['Shortform (Reels / TikTok / Shorts)', 'Longform (YouTube)', 'Podcast clipping', 'Monthly retainer', 'Not sure yet'],
        qty: 'Number of videos',
        qtyPh: 'e.g. 4',
        dur: 'Approximate final runtime',
        durPh: 'e.g. 60 seconds / 12 minutes',
        deadline: 'Deadline',
        footage: 'Footage link',
        footagePh: 'Google Drive / WeTransfer / Dropbox',
        notes: 'References & notes',
        notesPh: 'Edit styles you like, the mood, or anything else I should know.',
        optional: 'optional',
        required: 'required',
        sendWa: 'Send via WhatsApp →',
        sendMail: 'Send via Email →',
        subject: 'Project Brief — InnoProductions',
        missing: 'Add your name and project type first.',
        greeting: 'Hi InnoProductions, I would like to order a video edit.',
      },
    },
    footerMade: '© 2026 INNOSXNCE · MADE IN TANGERANG SELATAN',
    footerDisc:
      'All purchases are processed through Lynk.id. By buying, you agree to the terms that apply on that platform.',
  },
} as const

export type CopyType = typeof COPY
export type LangCopy = CopyType['id']
